export function getLanguage(ext) {
    const data = [
        { ext: 'js', lang: 'javascript' },
        { ext: 'jsx', lang: 'javascript' },
        { ext: 'ts', lang: 'typescript' },
        { ext: 'tsx', lang: 'typescript' },
        { ext: 'html', lang: 'html' },
        { ext: 'css', lang: 'css' },
        { ext: 'less', lang: 'less' },
        { ext: 'scss', lang: 'scss' },
        { ext: 'json', lang: 'json' },
        { ext: 'py', lang: 'python' },
        { ext: 'java', lang: 'java' },
        { ext: 'c', lang: 'c' },
        { ext: 'cpp', lang: 'cpp' },
        { ext: 'cs', lang: 'csharp' },
        { ext: 'go', lang: 'go' },
        { ext: 'php', lang: 'php' },
        { ext: 'rb', lang: 'ruby' },
        { ext: 'bat', lang: 'bat' },
        { ext: 'sh', lang: 'bat' },
        { ext: 'shell', lang: 'shell' },
        { ext: 'dart', lang: 'dart' },
        { ext: 'dockerfile', lang: 'dockerfile' },
        { ext: 'ini', lang: 'ini' },
        { ext: 'kts', lang: 'kotlin' },
        { ext: 'md', lang: 'markdown' },
        { ext: 'sql', lang: 'sql' },
        { ext: 'ps1', lang: 'powershell' },
        { ext: 'redis', lang: 'redis' },
        { ext: 'yaml', lang: 'yaml' },
        { ext: 'yml', lang: 'yaml' },
        { ext: 'xml', lang: 'xml' },
        { ext: 'vue', lang: 'vue' },
        { ext: 'rs', lang: 'rust' },
        { ext: 'swift', lang: 'swift' },
        { ext: 'r', lang: 'r' },
        { ext: 'groovy', lang: 'groovy' },
        { ext: 'hbs', lang: 'handlebars' },
        { ext: 'tex', lang: 'latex' }
    ]

    const found = data.find(item => item.ext === ext);
    return found ? found.lang : 'markdown'; // Default to 'markdown' if not found
}

export function getOption() {
    const option = {
        "acceptSuggestionOnCommitCharacter": true,
        "acceptSuggestionOnEnter": "on",
        "accessibilitySupport": "auto",
        "accessibilityPageSize": 10,
        "ariaLabel": "Editor content",
        "ariaRequired": false,
        "screenReaderAnnounceInlineSuggestion": true,
        "autoClosingBrackets": "languageDefined",
        "autoClosingComments": "languageDefined",
        "autoClosingDelete": "auto",
        "autoClosingOvertype": "auto",
        "autoClosingQuotes": "languageDefined",
        "autoIndent": "full",
        "autoSurround": "languageDefined",
        "bracketPairColorization": {
            "enabled": true,
            "independentColorPoolPerBracketType": false
        },
        "bracketPairGuides": {
            "bracketPairs": true,
            "bracketPairsHorizontal": "active",
            "highlightActiveBracketPair": true,
            "indentation": true,
            "highlightActiveIndentation": true
        },
        "stickyTabStops": true,
        "codeLens": true,
        "codeLensFontFamily": "",
        "codeLensFontSize": 0,
        "colorDecorators": true,
        "colorDecoratorActivatedOn": "clickAndHover",
        "colorDecoratorsLimit": 500,
        "columnSelection": false,
        "comments": {
            "insertSpace": true,
            "ignoreEmptyLines": true
        },
        "contextmenu": true,
        "copyWithSyntaxHighlighting": true,
        "cursorBlinking": "blink",
        "cursorSmoothCaretAnimation": "off",
        "cursorStyle": "line",
        "cursorSurroundingLines": 0,
        "cursorSurroundingLinesStyle": "default",
        "cursorWidth": 0,
        "disableLayerHinting": false,
        "disableMonospaceOptimizations": false,
        "domReadOnly": false,
        "dragAndDrop": true,
        "emptySelectionClipboard": true,
        "dropIntoEditor": {
            "enabled": true,
            "showDropSelector": "afterDrop"
        },
        "stickyScroll": {
            "enabled": false,
        },
        "experimentalWhitespaceRendering": "svg",
        "extraEditorClassName": "",
        "fastScrollSensitivity": 5,
        "find": {
            "cursorMoveOnType": true,
            "seedSearchStringFromSelection": "always",
            "autoFindInSelection": "never",
            "globalFindClipboard": false,
            "addExtraSpaceOnTop": true,
            "loop": true
        },
        "fixedOverflowWidgets": false,
        "folding": true,
        "foldingStrategy": "auto",
        "foldingHighlight": true,
        "foldingImportsByDefault": false,
        "foldingMaximumRegions": 5000,
        "unfoldOnClickAfterEndOfLine": false,
        "fontFamily": "Consolas, 'Courier New', monospace",
        "fontLigatures2": false,
        "fontSize": 14,
        "fontWeight": "normal",
        "fontVariations": false,
        "formatOnPaste": false,
        "formatOnType": false,
        "glyphMargin": true,
        "gotoLocation": {
            "multiple": null,
            "multipleDefinitions": "peek",
            "multipleTypeDefinitions": "peek",
            "multipleDeclarations": "peek",
            "multipleImplementations": "peek",
            "multipleReferences": "peek",
            "alternativeDefinitionCommand": "editor.action.goToReferences",
            "alternativeTypeDefinitionCommand": "editor.action.goToReferences",
            "alternativeDeclarationCommand": "editor.action.goToReferences",
            "alternativeImplementationCommand": "",
            "alternativeReferenceCommand": ""
        },
        "hideCursorInOverviewRuler": false,
        "hover": {
            "enabled": true,
            "delay": 300,
            "sticky": true,
            "hidingDelay": 300,
            "above": true
        },
        "inDiffEditor": false,
        "letterSpacing": 0,
        "lightbulb": {
            "enabled": "onCode"
        },
        "lineDecorationsWidth": 10,
        "lineHeight": 0,
        "lineNumbers": "on",
        "lineNumbersMinChars": 5,
        "linkedEditing": false,
        "links": true,
        "matchBrackets": "always",
        "minimap": {
            "enabled": false
        },
        "mouseStyle": "text",
        "mouseWheelScrollSensitivity": 1,
        "mouseWheelZoom": false,
        "multiCursorMergeOverlapping": true,
        "multiCursorModifier": "alt",
        "multiCursorPaste": "spread",
        "multiCursorLimit": 10000,
        "occurrencesHighlight": "singleFile",
        "overviewRulerBorder": true,
        "overviewRulerLanes": 2,
        "padding": {
            "top": 0,
            "bottom": 0
        },
        "pasteAs": {
            "enabled": true,
            "showPasteSelector": "afterPaste"
        },
        "parameterHints": {
            "enabled": true,
            "cycle": true
        },
        "peekWidgetDefaultFocus": "tree",
        "definitionLinkOpensInPeek": false,
        "quickSuggestions": {
            "other": "on",
            "comments": "off",
            "strings": "off"
        },
        "quickSuggestionsDelay": 10,
        "readOnly": false,
        "renameOnType": false,
        "renderControlCharacters": true,
        "renderFinalNewline": "on",
        "renderLineHighlight": "line",
        "renderLineHighlightOnlyWhenFocus": false,
        "renderValidationDecorations": "editable",
        "renderWhitespace": "selection",
        "revealHorizontalRightPadding": 15,
        "roundedSelection": true,
        "rulers": [],
        "scrollbar": {
            "vertical": "auto",
            "horizontal": "auto",
            "verticalScrollbarSize": 14,
            "horizontalScrollbarSize": 12,
            "scrollByPage": false,
            "ignoreHorizontalScrollbarInContentHeight": false
        },
        "scrollBeyondLastColumn": 4,
        "scrollBeyondLastLine": true,
        "scrollPredominantAxis": true,
        "selectionClipboard": true,
        "selectionHighlight": true,
        "selectOnLineNumbers": true,
        "showFoldingControls": "mouseover",
        "showUnused": true,
        "showDeprecated": true,
        "inlayHints": {
            "enabled": "on",
            "fontSize": 0,
            "fontFamily": "",
            "padding": false
        },
        "snippetSuggestions": "inline",
        "smartSelect": {
            "selectLeadingAndTrailingWhitespace": true,
            "selectSubwords": true
        },
        "smoothScrolling": false,
        "stopRenderingLineAfter": 10000,
        "suggest": {
            "insertMode": "insert",
            "filterGraceful": true,
            "localityBonus": false,
            "shareSuggestSelections": false,
            "selectionMode": "always",
            "snippetsPreventQuickSuggestions": false,
            "showIcons": true,
            "showStatusBar": false,
            "preview": false,
            "showInlineDetails": true,
            "maxVisibleSuggestions": 0,
            "filteredTypes": {},
            "showMethods": true,
            "showFunctions": true,
            "showConstructors": true,
            "showDeprecated": true,
            "matchOnWordStartOnly": true,
            "showFields": true,
            "showVariables": true,
            "showClasses": true,
            "showStructs": true,
            "showInterfaces": true,
            "showModules": true,
            "showProperties": true,
            "showEvents": true,
            "showOperators": true,
            "showUnits": true,
            "showValues": true,
            "showConstants": true,
            "showEnums": true,
            "showEnumMembers": true,
            "showKeywords": true,
            "showWords": true,
            "showColors": true,
            "showFiles": true,
            "showReferences": true,
            "showCustomcolors": true,
            "showFolders": true,
            "showTypeParameters": true,
            "showSnippets": true,
            "showUsers": true,
            "showIssues": true
        },
        "inlineSuggest": {
            "enabled": true,
            "showToolbar": "onHover",
            "suppressSuggestions": false,
            "fontFamily": "default"
        },
        "inlineEdit": {
            "enabled": false,
            "showToolbar": "onHover",
            "fontFamily": "default"
        },
        "inlineCompletionsAccessibilityVerbose": false,
        "suggestFontSize": 0,
        "suggestLineHeight": 0,
        "suggestOnTriggerCharacters": true,
        "suggestSelection": "first",
        "tabCompletion": "off",
        "tabIndex": 0,
        "unicodeHighlight": {
            "nonBasicASCII": "inUntrustedWorkspace",
            "invisibleCharacters": true,
            "ambiguousCharacters": true,
            "includeComments": "inUntrustedWorkspace",
            "includeStrings": true,
            "allowedCharacters": {},
            "allowedLocales": {
                "_os": true,
                "_vscode": true
            }
        },
        "unusualLineTerminators": "prompt",
        "useShadowDOM": true,
        "useTabStops": true,
        "wordBreak": "normal",
        "wordSegmenterLocales": [],
        "wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?",
        "wordWrap": "off",
        "wordWrapBreakAfterCharacters": " \t})]?|/&.,;¢°′″‰℃、。｡､￠，．：；？！％・･ゝゞヽヾーァィゥェォッャュョヮヵヶぁぃぅぇぉっゃゅょゎゕゖㇰㇱㇲㇳㇴㇵㇶㇷㇸㇹㇺㇻㇼㇽㇾㇿ々〻ｧｨｩｪｫｬｭｮｯｰ”〉》」』】〕）］｝｣",
        "wordWrapBreakBeforeCharacters": "([{‘“〈《「『【〔（［｛｢£¥＄￡￥+＋",
        "wordWrapColumn": 80,
        "wordWrapOverride1": "inherit",
        "wordWrapOverride2": "inherit",
        "defaultColorDecorators": false,
        "tabFocusMode": false,
        "wrappingIndent": {
            "wrappingIndent": "same"
        },
        "wrappingStrategy": {
            "wrappingStrategy": "simple"
        }
    }
    return option;
}